# Generated by Django 3.1.7 on 2021-02-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], max_length=15)),
                ('post_type', models.CharField(choices=[('staticpost', 'StaticPost'), ('videpost', 'VideoPost'), ('staticstory', 'StaticStory'), ('videostory', 'VideoStory'), ('reels', 'Reels'), ('carouselpost', 'CarouselPost')], max_length=15)),
            ],
        ),
    ]
